### Get Products
GET https://dummyjson.com/products


### Add a new product
### Add a new product
POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "New Product1",
  "description": "This is a new product.",
  "price": 100,
  "discountPercentage": 10,
  "rating": 4.5,
  "stock": 50,
  "brand": "BrandName",
  "thumbnail": "http://example.com/thumbnail.jpg"
}

###add to Cart
POST http://localhost:3000/products/cart
Content-Type: application/json

{
  "session_id": "12345",
  "product_id": "67890",
  "quantity": 2,
  "title": "New Product2",
  "description": "This is a new product.",
  "price": 100,
  "discountPercentage": 10,
  "rating": 4.5,
  "stock": 50,
  "brand": "BrandName",
  "thumbnail": "http://example.com/thumbnail.jpg"
}


### Get Product by ID
GET https://dummyjson.com/products/1

###for user registeration
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### User Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}